// Re-export all types from content.ts
export type {
  SiteSettings,
  Hero,
  CTAButton,
  About,
  QuickFact,
  Skills,
  SkillSubcategory,
  SkillCategory,
  Skill,
  Projects,
  Project,
  Impact,
  Experience,
  ExperienceEntry,
  Achievements,
  Achievement,
  Testimonials,
  Testimonial,
  PortfolioContent,
  ContentSection,
} from './content'
